application: godofinvestment
version: 2
runtime: python
api_version: 1

handlers:
- url: /cron/daily
  script: cron/daily.py
  login: admin

- url: /cron/1min
  script: cron/1min.py
  login: admin

- url: /env/init
  script: env/init.py
  login: admin

- url: /static
  static_dir: static 

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: index.py
